name: Publish tweet

on:
  schedule:
    - cron:  '0 */2 * * *'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Tweet
      run: |
        python app.py ${{ secrets.GOOGLE_DEVELOPER_KEY }} ${{ secrets.TWITTER_CONSUMER_KEY }} ${{ secrets.TWITTER_CONSUMER_SECRET }} ${{ secrets.TWITTER_ACCESS_KEY }} ${{ secrets.TWITTER_ACCESS_SECRET }}
